*** misc

this just generates a csv for my own testing. practically, csvs in the program are always in the right order since theyre not written except on close() so the ordering/naming here is irrelevant.

#+BEGIN_SRC elisp
(let ((cur (current-buffer))
      (tfmt "%s")
      (i 0))
  (with-current-buffer cur
    (goto-char (point-max))
    (while (< i (* 10 86400))
      (if (not (eq i 0)) (insert "\n"))
      (insert (format "filename%d.jpg," (- 10 (/ i 86400))))
      (insert (number-to-string
               (- (string-to-number (format-time-string tfmt (current-time)))
                  (let ((randoffset (random 100)) (sign (> (random 2) 0)))
                    (if sign (+ i randoffset) (- i randoffset)))))) ;add some variation
      (setq i (+ i 86400)))))
#+END_SRC
/(M-x org-babel-execute-src-block)/

*** py testing
**** ~class Meta~ test suite

#+BEGIN_SRC python
#suite test
def metatest(namespace):
    mymeta = namespace.Meta()
    mymeta.mwrite()
    mymeta.chsort(1,False)
    print('asc\n',list(mymeta.file_stream()))
    mymeta.chsort(1,True)
    print('dsc\n',list(mymeta.file_stream()))
    mymeta.insert(['myfile.jpg','1768686797'])
    print('insert img\n',list(mymeta.file_stream()))
    mymeta.chsort(1,False)
    print('chsort asc\n',list(mymeta.file_stream()))
    mymeta.insert(['otherfile.jpg','1769205103'])
    print('insert img\n',list(mymeta.file_stream()))
#+END_SRC

**** backend simulation

/uploading/converting/inserting into Meta obj/ - naive: ~create_task()~ upon upload, awaits exif/conversion before ~Meta.insert()~ call. however, that would mean insertion isn't done in upload-order, but upload-plus-/[exif extraction/conversion]/-order. need a way to enforce doing insertions in the order that files are uploaded.

two methods with asyncio queues in a consumer/producer like pattern. both examples: premade (file-) ~sizes~ list instead of producer, completely ignore upload time. (~process()~ -> conversion/exif)
#+BEGIN_SRC python
from concurrent.futures import ProcessPoolExecutor
import asyncio
# ...
executor = ProcessPoolExecutor()
asyncio.run(main())
#+END_SRC
1. conversion task is scheduled upon upload, consumer/listener only awaits it
   #+BEGIN_SRC python
async def process(size):
    loop = asyncio.get_event_loop()
    await loop.run_in_executor(executor,sum,range(50000000*size))
    print(f'processing complete for task of order {size}')
    return size
async def consumer():
    while True:
        next_task = await tasks.get()
        res = await next_task
        print(f'(resolved task of order {res})')
async def main():
    for x in sizes:
        #schedule on upload
        await tasks.put(asyncio.create_task(process(x)))
    asyncio.create_task(consumer())
    while True:
        await asyncio.sleep(1)
sizes = [5,1,6,2,3]
tasks = asyncio.Queue()
   #+END_SRC
2. listener/consumer schedules+awaits the conversion task
   #+BEGIN_SRC python
async def process(size):
    loop = asyncio.get_event_loop()
    await loop.run_in_executor(executor,sum,range(50000000 * size))
    print(f'processing complete for task of order {size}')
    return size
async def consumer():
    while True:
        next_task_size = await sizes.get()
        res = await process(next_task_size)
        print(f'(scheduled and resolved task)')
async def main():
    for x in sizes_l:
        await sizes.put(x)
    asyncio.create_task(consumer())
    while True:
        await asyncio.sleep(1)
sizes_l = [5,1,6,2,3]
sizes = asyncio.Queue()
   #+END_SRC

can't use time.sleep or asyncio.sleep for testing! changing ~sum~ to ~time.sleep(size)~ in the executor makes total processing time take only as long as longest process call (2 also takes much longer than 1). that's not accurate to what PIL does. the difference should be only in what conversions finish first.\\PIL is not async. subprocess seemed natural.

fleshed out example taking the first approach:
#+BEGIN_SRC python
_queue = asyncio.Queue()
executor = ProcessPoolExecutor()
filesizes = [5, 1, 6, 2, 3]
filen = len(filesizes)
async def uploader(): #like a bunch of upload requests
    i = 0
    while(i<filen):
        filesize = filesizes[i]
        await asyncio.sleep(1+filesize) #uploading takes longer than converting
        print(f'upload complete fsize {filesize}')
        #sched processing/converter task and push it immediately upon writing upload to fs
        handle = asyncio.create_task(processor(filesize))
        await _queue.put(handle)
        i+=1
async def consumer(): #insertion listener
    while True:
        nexttask = await _queue.get()
        exif = await nexttask
        print(f'\tdetected resolved task')
        insert(exif)
async def processor(size):
    loop = asyncio.get_event_loop()
    await loop.run_in_executor(executor,sum,range(50000000*size))
    exif = randrange(50,100) #converter.py can return exif data
    print(f'processing complete for a file of size {size}: \t{exif}')
    return exif
def insert(exif): #Meta.insert()
    print(f'\tinserting file via exif key {exif}')
async def main():
    asyncio.create_task(uploader())
    asyncio.create_task(consumer())
    while True:
        await asyncio.sleep(1)
#+END_SRC
-  the ~consumer~ task needs to be running with microdot app. (? or queue lifetime?)

*** test client
#+BEGIN_SRC bash
#upload 1 file
curl -X POST "http://localhost:4000/upload" \
    -T "/home/dunchaleo/Downloads/temp/filename2.jpg" \
    -H "Content-Type:application/octet-stream" \
    -H "filename:filename2.jpg"
#+END_SRC

testing multi file upload /(shouldnt expect this to upload files in any particular order)/. this works like html5 multi file picker dialog and ~await fetch('/upload', {})~ for file in files form, i.e. server response is recieved before uploading next file.
#+BEGIN_SRC elisp
;(testing multi upload until then)
(let* ((path (expand-file-name "~/Downloads/temp/"))
       (files (directory-files path))
       (fullpaths (mapcar (lambda (f) (concat path f)) files))
       (extensions (list ".jpg" ".jpeg" ".png" ".webp")))
  (dolist (file fullpaths)
    (dolist (ext extensions)
      (if (s-ends-with? ext file)
          (let ((command
                 (concat
                  "curl -X POST \"http://localhost:4000/upload\""
                  " -T " file
                  " -H \"filename:" (file-name-nondirectory file) "\"")))
            (shell-command command))))))
#+END_SRC

#+RESULTS:
*** testing output (csv generator)
    filename10.jpg,1769377865
    filename9.jpg,1769291542
    filename8.jpg,1769205102
    filename7.jpg,1769118831
    filename6.jpg,1769032272
    filename5.jpg,1768945861
    filename4.jpg,1768859492
    filename3.jpg,1768773215
    filename2.jpg,1768686796
    filename1.jpg,1768600416
