*** misc
    this just generates a csv for my own testing. practically, csvs in the program are always in the right order since theyre not written except on close() so the ordering/naming here is irrelevant.
    #+BEGIN_SRC elisp
    (let ((cur (current-buffer))
        (tfmt "%s")
          (i 0))
      (with-current-buffer cur
        (goto-char (point-max))
        (while (< i (* 10 86400))
          (if (not (eq i 0)) (insert "\n"))
          (insert (format "filename%d.jpg," (- 10 (/ i 86400))))
          (insert (number-to-string
                   (- (string-to-number (format-time-string tfmt (current-time)))
                      (let ((randoffset (random 100)) (sign (> (random 2) 0)))
                        (if sign (+ i randoffset) (- i randoffset)))))) ;add some variation
          (setq i (+ i 86400)))))
    #+END_SRC
    /(M-x org-babel-execute-src-block)/
*** py testing
**** ~class Meta~ test suite
#+BEGIN_SRC python
#suite test
def metatest(namespace):
    mymeta = namespace.Meta()
    mymeta.mwrite()
    mymeta.chsort(1,False)
    print('asc\n',list(mymeta.file_stream()))
    mymeta.chsort(1,True)
    print('dsc\n',list(mymeta.file_stream()))
    mymeta.insert(['myfile.jpg','1768686797'])
    print('insert img\n',list(mymeta.file_stream()))
    mymeta.chsort(1,False)
    print('chsort asc\n',list(mymeta.file_stream()))
    mymeta.insert(['otherfile.jpg','1769205103'])
    print('insert img\n',list(mymeta.file_stream()))
#+END_SRC
**** backend simulation
/uploading/converting/inserting into Meta obj/
(~_queue = asyncio.Queue()~, set i&lim, then ~asyncio.run(main())~):
#+BEGIN_SRC python
async def uploader(): #like a bunch of upload requests (lim)
    global i
    global lim
    while(i<lim):
        filesize = randrange(1,6) #note: helpful for understanding: test instant uploads too
        await asyncio.sleep(1+filesize) #uploading takes longer than converting
        print(f'upload complete fsize {filesize}')
        handle = asyncio.create_task(processor(filesize)) #file processing/converter task
        await _queue.put(handle) #push task immediately upon writing upload to fs
        i+=1
async def consumer(): #from consumer/producer pattern
    while True:
        nexttask = await _queue.get()
        exif = await nexttask
        print(f'detected task resolution')
        #insert(exif)
#        _queue.task_done() #necessary? you can do this on non-task items
async def processor(size):
    #NOTE PIL is blocking!! what to do?
    await asyncio.sleep(size)
    exif = randrange(50,100) #converter.py can return exif data
    print(f'processing complete for a file of size {size}: \t{exif}')
    return exif
#def insert(exif): #Meta.insert()
#    print(f'inserting file via exif key {exif}')
async def main():
    asyncio.create_task(uploader())
    asyncio.create_task(consumer())
    while True:
        await asyncio.sleep(1)

#+END_SRC
- this is a way to enforce doing insertions in the order that files are uploaded. it would have been more straightforward to ~create_task~ upon upload, and have that await exif/conversion before ~Meta.insert()~ call. however, that would mean insertion isn't done in upload-order, but upload-plus-[exif extraction/conversion]-order. the ~consumer~ task needs to be running with microdot app. (? or queue lifetime?)
- PIL is not async! processor (converter) has to be on another thread to use the code the same way. or, it could just block (consequences?).

*** test client
#+BEGIN_SRC bash
#upload 1 file
curl -X POST "http://localhost:4000/upload" \
    -T "/home/dunchaleo/Downloads/temp/filename2.jpg" \
    -H "Content-Type:application/octet-stream" \
    -H "filename:filename2.jpg"
#+END_SRC

#+RESULTS:

testing multi file upload /(shouldnt expect this to upload files in any particular order)/. this works like html5 multi file picker dialog and ~await fetch('/upload', {})~ for file in files form, i.e. server response is recieved before uploading next file.
#+BEGIN_SRC elisp
;(testing multi upload until then)
(let* ((path (expand-file-name "~/Downloads/temp/"))
       (files (directory-files path))
       (fullpaths (mapcar (lambda (f) (concat path f)) files))
       (extensions (list ".jpg" ".jpeg" ".png" ".webp")))
  (dolist (file fullpaths)
    (dolist (ext extensions)
      (if (s-ends-with? ext file)
          (let ((command
                 (concat
                  "curl -X POST \"http://localhost:4000/upload\""
                  " -T " file
                  " -H \"filename:" (file-name-nondirectory file) "\"")))
            (shell-command command))))))
#+END_SRC

#+RESULTS:
*** testing output (csv generator)
    filename10.jpg,1769377865
    filename9.jpg,1769291542
    filename8.jpg,1769205102
    filename7.jpg,1769118831
    filename6.jpg,1769032272
    filename5.jpg,1768945861
    filename4.jpg,1768859492
    filename3.jpg,1768773215
    filename2.jpg,1768686796
    filename1.jpg,1768600416
